remove from_dec_str and use const instead for tick_math
0xKitsune/uniswap_v3_math pull request #31
Opened 2023-09-18 19:31 UTC by lakshya-sky

only for tick_math:
use constants instead of from_dec_str which requires more cpu cycles than constants.

2023-09-18 22:40 UTC, 0xKitsune requested changes

2023-09-18 22:40 UTC, 0xKitsune commented on src/tick_math.rs
> +
Can you change the name to `SQRT_10001`,`TICK_LOW` and `TICK_HIGH`?

Also can you move these up with the rest of the constants?

2023-09-19 16:39 UTC, 0xOsiris commented
LGTM

2023-09-19 16:45 UTC, 0xKitsune approved these changes

2023-09-19 16:45 UTC, merged